config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  as :account do
    get 'accounts/edit' => 'devise/registrations#edit', :as => 'edit_account_registration'
    put 'accounts' => 'devise/registrations#update', :as => 'account_registration'
  end
  get 'accounts/sign_out', to: 'blogs#index'
  get 'blogconfigs/inde', to: 'blogconfigs#inde'
  get 'bloggenres/inde', to: 'bloggenres#inde'
  get 'blogposts/inde', to: 'blogposts#inde'
  get 'blogconfigs/login_check'
  get 'bloggenres/login_check'
  get 'blogposts/login_check'

  get '/', to: 'blogs#index'
  get 'blogs/index'
  get 'blogs', to: 'blogs#index'
  get 'blogs/:page', to: 'blogs#index'

  get 'blogs/genre/:id', to: 'blogs#genre'
  get 'blogs/genre/:id/:page', to: 'blogs#genre'

  get 'blogs/show/:id', to: 'blogs#show'

  get 'blogposts/index'
  get 'blogposts', to: 'blogposts#index'

  get 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete', to: 'blogposts#delete'
  post 'blogposts/delete/:id', to: 'blogposts#delete'

  get 'blogposts/add'
  post 'blogposts/add'

  get 'blogposts/:id', to: 'blogposts#edit'
  patch 'blogposts/:id', to: 'blogposts#edit'

  get 'blogposts/delete'

  get 'bloggenres/index'
  get 'bloggenres', to: 'bloggenres#index'

  get 'bloggenres/add'
  post 'bloggenres/add'

  get 'bloggenres/:id', to: 'bloggenres#edit'
  patch 'bloggenres/:id', to: 'bloggenres#edit'

  get 'blogconfigs/index'
  get 'blogconfig/:id', to: 'blogconfigs#index'

  get 'blogconfigs/edit'
  patch 'blogconfigs/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogconfig.rb
class Blogconfig < ApplicationRecord
	validates :title, :stylename, presence: {message:'は、必須項目です。'}
end

app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
	has_many :blogpost


	validates :name, presence: {message:'は、必須項目です。'}
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
	belongs_to :bloggenre
	
	validates :title, :content, presence: {message:'は、必須項目です。'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogconfigs_controller.rb
class BlogconfigsController < ApplicationController
	layout 'blogconfigs'
	before_action :authenticate_account!, only: [:login_check, :edit, :index]

	def inde
		@msg = 'this is sample page.'
	end


	def login_check
		@account = current_account
		@msg = 'you logined ' 
	end


	def index
		@blogconfig = Blogconfig.find 1
	end


	def edit
		@blogconfig = Blogconfig.find 1
		if request.patch? then
			@blogconfig.update blogconfig_params
			redirect_to '/blogconfigs/index'
		end
	end


	private
	def blogconfig_params
		params.require(:blogconfig).permit(:title, :subtitle, :stylename)
	end


end

app/controllers/bloggenres_controller.rb
class BloggenresController < ApplicationController
	layout 'bloggenres'
	before_action :authenticate_account!, only: [:login_check, :edit, :index, :add]

	def inde
		@msg = 'this is sample page.'
	end


	def login_check
		@account = current_account
		@msg = 'you logined ' 
	end


	def index
		@data = Bloggenre.all
	end


	def add
		@bloggenre = Bloggenre.new
		if request.post? then
			@bloggenre = Bloggenre.create bloggenre_params
			redirect_to '/bloggenres'
		end
	end


	def edit
		@bloggenre = Bloggenre.find params[:id]
		if request.patch? then
			@bloggenre.update bloggenre_params
			redirect_to '/bloggenres'
		end
	end


	private
	def bloggenre_params
		params.require(:bloggenre).permit(:name, :memo)
	end


end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
	layout 'blogposts'
	before_action :authenticate_account!, only: [:login_check, :edit, :index, :add, :delete]

	def inde
		@msg = 'this is sample page.'
	end


	def login_check
		@account = current_account
		@msg = 'you logined ' 
	end



	def index
		@data = Blogpost.all.order('created_at desc')
	end


	def add
		@blogpost = Blogpost.new
		@genres = Bloggenre.all
		if request.post? then
			@blogpost = Blogpost.create blogposts_params
			redirect_to '/blogposts'
		end
	end


	def edit
		@blogpost = Blogpost.find params[:id]
		@genres = Bloggenre.all
		if request.patch? then
			@blogpost.update blogposts_params
			redirect_to '/blogposts'
		end
	end


	def delete
		@blogpost = Blogpost.find(params[:id])
		if request.post? then
			@blogpost.destroy
			redirect_to '/blogposts'
		end
	end


	private
	def blogposts_params
		params.require(:blogpost).permit(:title, :read, :songtitle, :songurl, :content, :bloggenre_id)
	end


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	layout 'blogs'


	def index
		page_size = 5
		@page_num = 0
		if params[:page] != nil then
			@page_num = params[:page].to_i
		end
		@data = Blogpost.all.order('updated_at desc')
			.offset(page_size * @page_num)
			.limit(page_size)
		@blogconfig = Blogconfig.find 1
	end


	def genre
		page_size = 5
		@page_num = 0
		if params[:page] != nil then
			@page_num = params[:page].to_i
		end
		@genre = Bloggenre.find params[:id]
		@data = Blogpost.where('bloggenre_id = ?',params[:id])
			.order('created_at desc').offset(page_size * @page_num)
			.limit(page_size)
		@blogconfig = Blogconfig.find 1
	end


	def show
		@blogpost = Blogpost.find params[:id]
		@blogconfig = Blogconfig.find 1
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
    require "redcarpet"
    require "coderay"

    class HTMLwithCoderay < Redcarpet::Render::HTML
        def block_code(code, language)
            language = language.split(':')[0]

            case language.to_s
            when 'rb'
                lang = 'ruby'
            when 'yml'
                lang = 'yaml'
            when 'css'
                lang = 'css'
            when 'html'
                lang = 'html'
            when ''
                lang = 'md'
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
    end

    def markdown(text)
        html_render = HTMLwithCoderay.new(filter_html: false, hard_wrap: true,fenced_code_blocks: true,)
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            disable_indented_code_blocks: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text)
    end
end

app/helpers/blogconfigs_helper.rb
module BlogconfigsHelper
end

app/helpers/bloggenres_helper.rb
module BloggenresHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogconfigs/edit.html.erb
<h1>Blogconfigs#edit</h1>
<p>※ブログ設定の編集</p>
<% if @blogconfig.errors.any? %>
<ul>
	<% @blogconfig.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
</ul>
<% end %>
<table>
	<%= form_for(@blogconfig, url:{controller:'blogconfigs', action:'edit'}) do |form| %>
	<tr><th>Title</th>
		<td><%= form.text_field :title %></td></tr>
	<tr><th>Subtitle</th>
		<td><%= form.text_field :subtitle %></td></tr>
	<tr><th>Style name</th>
		<td><%= form.text_field :stylename %></td></tr>
	<tr><th></th>
		<td><%= form.submit "送信" %></td></tr>
	<% end %>
</table>

app/views/blogconfigs/inde.html.erb
<h1>blogconfigs#inde</h1>
<p><%= @msg %></p>
<hr>
<div><%=link_to 'go to login_check page!&gt;&gt;'.html_safe, {action:'login_check'} %></div>
<div><%= link_to "Sign out&gt;&gt;".html_safe, destroy_account_session_path, method: :delete %></div>

app/views/blogconfigs/index.html.erb
<h1>Blogconfigs#index</h1>
<p>※ブログの設定内容</p>
<table>
	<tr><th>Title</th>
		<td><%= @blogconfig.title %></td></tr>
	<tr><th>Subtitle</th>
		<td><%= @blogconfig.subtitle %></td></tr>
	<tr><th>Style Name</th>
		<td><%= @blogconfig.stylename %></td></tr>
	</tr>
</table>
<p><a href="/blogconfigs/edit">編集画面＞＞</a></p>

app/views/blogconfigs/login_check.html.erb
<h1><%= @account.email %></h1>
<p><%= @msg %></p>

app/views/bloggenres/add.html.erb
<h1>Bloggenres#add</h1>
<p>※ジャンル・データの作成</p>
<% if @bloggenre.errors.any? %>
<ul>
	<% @bloggenre.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
</ul>
<% end %>
<table>
	<%= form_for(@bloggenre, url:{controller:'bloggenres', action:'add'}) do |form| %>
	<tr><th>name</th>
		<td><%= form.text_field :name %></td></tr>
	<tr><th>memo</th>
		<td><%= form.text_field :memo %></td></tr>
	<tr><th></th>
		<td><%= form.submit "送信" %></td></tr>
	<% end %>
</table>

app/views/bloggenres/edit.html.erb
<h1>Bloggenres#edit</h1>
<p>※「<%= @bloggenre.name %>」ジャンルの編集</p>
<% if @bloggenre.errors.any? %>
<ul>
	<% @bloggenre.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
</ul>
<% end %>
<table>
	<%= form_for(@bloggenre, url:{controller:'bloggenres', action:'edit'}) do |form| %>
	<tr><th>Title</th>
		<td><%= form.text_field :name %></td></tr>
	<tr><th>Subtitle</th>
		<td><%= form.text_field :memo %></td></tr>
	<tr><th></th>
		<td><%= form.submit "送信" %></td></tr>
	<% end %>
</table>

app/views/bloggenres/inde.html.erb
<h1>bloggenres#inde</h1>
<p><%= @msg %></p>
<hr>
<div><%=link_to 'go to login_check page!&gt;&gt;'.html_safe, {action:'login_check'} %></div>
<div><%= link_to "Sign out&gt;&gt;".html_safe, destroy_account_session_path, method: :delete %></div>

app/views/bloggenres/index.html.erb
<h1>Bloggenres#index</h1>
<p>※ジャンル・データの一覧</p>
<table>
	<tr>
		<th>Id</th><th >name</th><th>memo</th><th></th>
	</tr>
	<% @data.each do |obj| %>
	<tr>
		<td><%= obj.id %></td>
		<td><%= obj.name %></td>
		<td><%= obj.memo %></td>
		<td><a href="/bloggenres/<%= obj.id %>">Edit</a></td>
	</tr>
	<% end %>
</table>
<p><a href="/bloggenres/add">新規作成＞＞</a></p>

app/views/bloggenres/login_check.html.erb
<h1><%= @account.email %></h1>
<p><%= @msg %></p>

app/views/blogposts/add.html.erb
<h1>Blogposts#add</h1>
<p>※ブログの記事の投稿</p>
<% if @blogpost.errors.any? %>
<ul>
	<% @blogpost.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
</ul>
<% end %>
<table>
	<%= form_for(@blogpost, url:{controller:'blogposts', action:'add'}) do |form| %>
	<tr><th>Title</th>
		<td><%= form.text_field :title %></td></tr>
	<tr><th>Read</th>
		<td><%= form.text_field :read %></td></tr>
	<tr><th>SongTitle</th>
		<td><%= form.text_field :songtitle %></td></tr>
	<tr><th>SongUrl</th>
		<td><%= form.text_field :songurl %></td></tr>
	<tr><th>Content</th>
		<td><%= form.text_area :content , {cols:100, rows:100} %></td></tr>
	<tr><th>Genre ID</th>
		<td><%= form.text_field :bloggenre_id %></td></tr>
	<tr><th></th>
		<td><%= form.submit "送信" %></td></tr>
	<% end %>
</table>
<hr>
<p>※ジャンルの一覧</p>
<table>
	<tr>
		<th>Id</th><th >Genre</th>
	</tr>
	<% @genres.each do |obj| %>
	<tr>
		<td><%= obj.id %></td>
		<td><%= obj.name %></td>
	</tr>
	<% end %>
</table>

app/views/blogposts/delete.html.erb
<h1>Blogposts#delete</h1>
<p>※以下を削除してもいいですか？</p>
<table>
	<tr><th>Id</th>
		<td><%= @blogpost.id %></td></tr>
	<tr><th>title</th>
		<td><%= @blogpost.title %></td></tr>
	<tr><th>read</th>
		<td><%= @blogpost.read %></td></tr>
	<tr><th>songtitle</th>
		<td><%= @blogpost.songtitle %></td></tr>
	<tr><th>songurl</th>
		<td><%= @blogpost.songurl %></td></tr>
	<tr><th>content</th>
		<td><%= @blogpost.content %></td></tr>
</table>
<%= form_tag controller: "blogposts", action: "delete" do %>
	<%= hidden_field_tag "id", {value: @blogpost.id} %>
	<%= submit_tag "送信" %>
<% end %>

app/views/blogposts/edit.html.erb
<h1>Blogposts#edit</h1>
<p>※「<%= @blogpost.title %>」の編集</p>
<% if @blogpost.errors.any? %>
<ul>
	<% @blogpost.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
</ul>
<% end %>
<table>
	<%= form_for(@blogpost, url:{controller:'blogposts', action:'edit'}) do |form| %>
	<tr><th>name</th>
		<td><%= form.text_field :title %></td></tr>
	<tr><th>memo</th>
		<td><%= form.text_field :read %></td></tr>
	<tr><th>songtitle</th>
		<td><%= form.text_field :songtitle %></td></tr>
	<tr><th>songurl</th>
		<td><%= form.text_field :songurl %></td></tr>
	<tr><th>message</th>
		<td><%= form.text_area :content, {cols:40, rows:10} %></td></tr>
	<tr><th>Genre ID</th>
		<td><%= form.text_field :bloggenre_id %></td></tr>
	<tr><th></th>
		<td><%= form.submit "送信" %></td></tr>
	<% end %>
</table>
<hr>
<p>※ジャンルの一覧</p>
<table>
	<tr>
		<th>Id</th><th >Genre</th>
	</tr>
	<% @genres.each do |obj| %>
	<tr>
		<td><%= obj.id %></td>
		<td><%= obj.name %></td>
	</tr>
	<% end %>
</table>

app/views/blogposts/inde.html.erb
<h1>blogposts#inde</h1>
<p><%= @msg %></p>
<hr>
<div><%=link_to 'go to login_check page!&gt;&gt;'.html_safe, {action:'login_check'} %></div>
<div><%= link_to "Sign out&gt;&gt;".html_safe, destroy_account_session_path, method: :delete %></div>

app/views/blogposts/index.html.erb
<h1>Blogposts#index</h1>
<p>※投稿記事の一覧</p>
<table>
	<tr>
		<th>Id</th><th >title</th><th>read</th>
			<th>genre</th><th colspan="2"></th>
	</tr>
	<% @data.each do |obj| %>
	<tr>
		<td><%= obj.id %></td>
		<td><%= obj.title %></td>
		<td><%= obj.read %></td>
 		
		<td><a href="/blogposts/<%= obj.id %>">Edit</a></td>
		<td><a href="/blogposts/delete/<%= obj.id %>">Delete</a></td>
	</tr>
	<% end %>
</table>
<p><a href="/blogposts/add">新規作成＞＞</a></p>

app/views/blogposts/login_check.html.erb
<h1><%= @account.email %></h1>
<p><%= @msg %></p>

app/views/blogs/genre.html.erb
<h3 class="category">★　Category :【<%= @genre.name %>】　★</h3>
<% @data.each do |obj| %>
	<h3 class="top_title"><a href="/blogs/show/<%= obj.id %>">
		‣<%= obj.title %></a></h3>
	<p class="top_read"><%= obj.read %><span class="created">
		【<%= obj.updated_at.strftime("%Y-%m-%d %H:%M") %>】<span></p>
	<hr>
<% end %>
<div class="navigate">
	<% if @page_num > 0 then %>
		<a href="/blogs/genre/<%= @genre.id.to_s + '/' + 
			(@page_num - 1).to_s %>">←Back</a>
	<% end %>
	<span>　</span>
	<a href="/blogs/genre/<%= @genre.id.to_s + '/' + (@page_num + 1)
		.to_s %>">Next→</a>
</div>

app/views/blogs/index.html.erb
<% @data.each do |obj| %>
	<h3 class="top_title"><a href="/blogs/show/<%= obj.id %>">
		<%= '‣' + obj.title %></a>
	</h3>
	
	<p class="top_read"><%= obj.read %><span class="top_created">
		(<%= obj.updated_at.strftime("%Y-%m-%d %H:%M") %>)</span></p>
	<hr>
<% end %>
<div class="navigate">
	<% if @page_num > 0 then %>
		<a href="/blogs/<%= @page_num - 1 %>">←Back</a>
	<% end %>
	<span>　</span>
	<a href="/blogs/<%= @page_num + 1 %>">Next→</a>
</div>

app/views/blogs/show.html.erb
<h3 class="show_title"><%= '‣' + @blogpost.title %></h3> 
<p class="show_read"><%= @blogpost.read + '【' + 
		@blogpost.bloggenre.name + '】' %>
		<a href= "<%= @blogpost.songurl %>" target="_blank">
		<i class="fas fa-headphones fa-4x fa-pull-right"></i></a>
		</p>

<div class="show_song">
	<a href="<%= @blogpost.songurl %>" target="_blank">Today's music:【<%= @blogpost.songtitle %>】</a>
</div> 
<div class="show_content">
	<%= markdown(@blogpost.content).html_safe %>


</div>
<p class="show_created">(<%= @blogpost.updated_at.strftime("%Y-%m-%d %H:%M") %>)</p>
<div class="navigate">
		<a href="/blogs">←Back</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-153574037-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-153574037-1');
  </script>

  <title>Takukin</title>
  <link rel="icon" href="/o.png" type="image/png" />

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/layouts/blogconfigs.html.erb
<!DOCTYPE html>
<html>
<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-153574037-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];

		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('js', new Date());

		gtag('config', 'UA-153574037-1');
	</script>
	<title>Takukin</title>
	<link rel="icon" href="/o.png" type="image/png" />

	<%= csrf_meta_tags %>


	<%= stylesheet_link_tag 'blogconfigs', 
			'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'blogconfigs', 
			'data-turbolinks-track': 'reload' %>
</head>


<body>
	<%= yield %>
</body>
</html>

app/views/layouts/bloggenres.html.erb
<!DOCTYPE html>
<html>
<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-153574037-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];

		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('js', new Date());

		gtag('config', 'UA-153574037-1');
	</script>
	<title>Takukin</title>
	<link rel="icon" href="/o.png" type="image/png" />


	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag 'bloggenres', 
			'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'bloggenres', 
			'data-turbolinks-track': 'reload' %>
</head>


<body>
	<%= yield %>
</body>
</html>

app/views/layouts/blogposts.html.erb
<!DOCTYPE html>
<html>
<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-153574037-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];

		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('js', new Date());

		gtag('config', 'UA-153574037-1');
	</script>

	<title>Takukin</title>
	<link rel="icon" href="/o.png" type="image/png" />

	<%= csrf_meta_tags %>


	<%= stylesheet_link_tag 'blogposts', 
			'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'blogposts', 
			'data-turbolinks-track': 'reload' %>
</head>


<body>
	<%= yield %>
</body>
</html>

app/views/layouts/blogs.html.erb
<!DOCTYPE html>
<html>
<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-153574037-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];

		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('js', new Date());

		gtag('config', 'UA-153574037-1');
	</script>

	<title>Takukin</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="icon" href="/o.png" type="image/png" />
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
		integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
	<%= csrf_meta_tags %>


	<%stylesheet_link_tag 'blogs', 
			'data-turbolinks-track': 'reload' %>
	<%= stylesheet_link_tag @blogconfig.stylename, 
			'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'blogs', 
			'data-turbolinks-track': 'reload' %>


</head>


<body>
	<div class="wrap">
		<header id="header">

			<div align="center">
				<h1><a href="/blogs"><img src="/logo2.png" class="logo_button" ontouchstart="" alt="TAG index" border="2"></a>
				</h1>
			</div>
			<a href="https://bitbucket.org/dashboard/repositories" target="_blank"><i
					class="fab fa-bitbucket fa-3x fa-pull-right"></i></a>
			<a href="https://www.instagram.com/maple_taku/?hl=ja" target="_blank"><i
					class="fab fa-instagram fa-3x fa-pull-right"></i></a>
			<a href="https://twitter.com/taku64150873" target="_blank"><i class="fab fa-twitter fa-3x fa-pull-right"></i></a>
			<a href="mailto:hayatsutkm&#64;gmail.com"><i class="fab fas fa-envelope fa-3x fa-pull-right"></i></a>
			<div class="subtiltle">
				<h2><%= @blogconfig.subtitle %></h2>
			</div>
		</header>
		<%
=begin%>
		<hr>
		<%
=end%>
		<main id="main">
			<%= yield %>
		</main>
		<div id="side">
			<% Bloggenre.all.each do |genre| %>
			<p><a href="/blogs/genre/<%= genre.id %>" class="btn-flat-border">
					<%= genre.name %></a></p>
			<% end %>
		</div>
		<%
=begin%>
		<main id="main">
			<%= yield %>
		</main>
		<%
=end%>
	</div>
</body>
</html>